- id: oaf-pre-commit-hook-git-branch
  name: OAF Git Branching Model
  description: Pre-commit hook to validate Git branching naming per GitFlow convention
  entry: oaf-pre-commit-hook-git-branch
  language: python
  stages: [post-checkout, commit, push, manual]
  args: [--force=True]

- id: oaf-pre-commit-hook-git-commit
  name: OAF Git Semantic Commit
  description: Pre-commit hook to validate conventional commit
  entry: oaf-pre-commit-hook-git-commit
  language: python
  stages: [commit-msg, prepare-commit-msg, manual]
  args: [--force=True]
