- id: oaf-tech-pre-commit-hook
  name: OAF Source Control Standards
  description: Pre-commit hook to validate ITD best practices and technical standards
  entry: oaf-tech-pre-commit-hook
  language: python
  #stages: [post-checkout, commit, commit-msg, prepare-commit-msg, push, manual]
  args: [--forced=False, --verbose=True]
